#!/usr/bin/env python3
"""
Test script for template generation functionality.
This script tests the Excel and PDF template generation features.
"""

import sys
import os
import tempfile

# Add the project root to the Python path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from school_system.services.student_service import StudentService
from school_system.services.class_management_service import ClassManagementService
from school_system.models.student import Student


def create_mock_students():
    """Create mock student data for testing."""
    students = [
        Student("2024001", "John Doe", "Red"),
        Student("2024002", "Jane Smith", "Blue"),
        Student("2024003", "Bob Johnson", "Red"),
        Student("2024004", "Alice Brown", "Green"),
        Student("2024005", "Charlie Wilson", "Blue"),
    ]

    # Set admission numbers
    for student in students:
        student.admission_number = student.student_id

    return students


def test_excel_template_generation():
    """Test Excel template generation."""
    print("🧪 Testing Excel Template Generation")
    print("=" * 40)

    try:
        import pandas as pd
        from datetime import datetime

        students = create_mock_students()

        # Create DataFrame
        data = {
            'School_Name': ['School Management System'] * len(students),
            'Class_Form': ['4'] * len(students),
            'Stream': ['Red'] * len(students),
            'Subject': ['Mathematics'] * len(students),
            'Student_Name': [student.name for student in students],
            'Admission_Number': [student.admission_number for student in students],
            'Book_Number': [''] * len(students),
            'Date_Borrowed': [''] * len(students),
            'Librarian_Name': ['admin'] * len(students),
            'Generated_Date': [datetime.now().strftime('%Y-%m-%d')] * len(students)
        }

        df = pd.DataFrame(data)
        print("✓ DataFrame created successfully")
        print(f"✓ DataFrame shape: {df.shape}")
        print(f"✓ Columns: {list(df.columns)}")

        # Test Excel file creation
        with tempfile.NamedTemporaryFile(delete=False, suffix='.xlsx') as tmp_file:
            excel_file = tmp_file.name

        df.to_excel(excel_file, index=False)
        print(f"✓ Excel file created: {excel_file}")

        # Verify file exists and has content
        if os.path.exists(excel_file):
            file_size = os.path.getsize(excel_file)
            print(f"✓ File size: {file_size} bytes")

            if file_size > 1000:  # Should be more than 1KB
                print("✅ Excel template generation test PASSED")
                return True
            else:
                print("❌ Excel file seems too small")
                return False
        else:
            print("❌ Excel file was not created")
            return False

    except ImportError as e:
        print(f"❌ Missing required library: {e}")
        print("Please install required packages:")
        print("  pip install pandas openpyxl")
        return False
    except Exception as e:
        print(f"❌ Excel template generation failed: {e}")
        return False


def test_pdf_template_generation():
    """Test PDF template generation."""
    print("\n🧪 Testing PDF Template Generation")
    print("=" * 40)

    try:
        from fpdf import FPDF
        from datetime import datetime

        students = create_mock_students()

        # Create PDF
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", size=12)

        # Header
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, "SCHOOL MANAGEMENT SYSTEM", ln=True, align='C')
        pdf.cell(0, 10, "BOOK BORROWING TEMPLATE", ln=True, align='C')
        pdf.ln(10)

        # Template details
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 8, "Class/Form: 4", ln=True)
        pdf.cell(0, 8, "Stream: Red", ln=True)
        pdf.cell(0, 8, "Subject: Mathematics", ln=True)
        pdf.cell(0, 8, "Generated by: admin", ln=True)
        pdf.cell(0, 8, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
        pdf.ln(10)

        # Table headers
        pdf.set_font("Arial", 'B', 10)
        headers = ["#", "Student Name", "Admission No.", "Book Number", "Signature"]
        col_widths = [15, 60, 30, 35, 40]

        for i, header in enumerate(headers):
            pdf.cell(col_widths[i], 8, header, border=1, align='C')
        pdf.ln()

        # Table data
        pdf.set_font("Arial", size=9)
        for i, student in enumerate(students, 1):
            pdf.cell(col_widths[0], 6, str(i), border=1, align='C')
            pdf.cell(col_widths[1], 6, student.name[:25], border=1)
            admission = student.admission_number or str(student.student_id)
            pdf.cell(col_widths[2], 6, admission, border=1, align='C')
            pdf.cell(col_widths[3], 6, "", border=1, align='C')
            pdf.cell(col_widths[4], 6, "", border=1, align='C')
            pdf.ln()

        # Create temporary file
        with tempfile.NamedTemporaryFile(delete=False, suffix='.pdf') as tmp_file:
            pdf_file = tmp_file.name

        pdf.output(pdf_file)
        print("✓ PDF file created successfully")

        # Verify file exists and has content
        if os.path.exists(pdf_file):
            file_size = os.path.getsize(pdf_file)
            print(f"✓ File size: {file_size} bytes")

            if file_size > 1000:  # Should be more than 1KB
                print("✅ PDF template generation test PASSED")
                return True
            else:
                print("❌ PDF file seems too small")
                return False
        else:
            print("❌ PDF file was not created")
            return False

    except ImportError as e:
        print(f"❌ Missing required library: {e}")
        print("Please install required packages:")
        print("  pip install fpdf")
        return False
    except Exception as e:
        print(f"❌ PDF template generation failed: {e}")
        return False


def test_template_data_preparation():
    """Test template data preparation logic."""
    print("\n🧪 Testing Template Data Preparation")
    print("=" * 40)

    try:
        # Mock class management service
        class ClassManagementService:
            def get_all_class_levels(self):
                return [4, 10, 11, 12]

            def get_class_stream_combinations(self):
                return [
                    (4, "Red", 25),
                    (4, "Blue", 22),
                    (10, "Science", 30),
                    (11, "Arts", 28)
                ]

            def get_students_by_class_level(self, class_level):
                return create_mock_students()[:class_level % 5 + 1]

            def get_students_by_class_and_stream(self, class_level, stream):
                return create_mock_students()[:3]

        # Mock student service
        class StudentService:
            def get_all_students(self):
                return create_mock_students()

        cms = ClassManagementService()
        ss = StudentService()

        # Test individual class templates
        class_templates = {}
        class_levels = cms.get_all_class_levels()

        for class_level in class_levels:
            students = ss.get_all_students()[:class_level % 5 + 1]  # Mock students
            if students:
                template_key = f"Form_{class_level}_All_Streams"
                class_templates[template_key] = students

        print(f"✓ Class templates created: {len(class_templates)}")
        for key, students in class_templates.items():
            print(f"  - {key}: {len(students)} students")

        # Test stream-subject templates
        stream_templates = {}
        combinations = cms.get_class_stream_combinations()

        subjects = ["Mathematics", "English", "Science", "History"]

        for class_level, stream, count in combinations:
            students = cms.get_students_by_class_and_stream(class_level, stream)
            if students:
                for subject in subjects:
                    template_key = f"Form_{class_level}_{stream}_{subject}"
                    stream_templates[template_key] = students

        print(f"✓ Stream-subject templates created: {len(stream_templates)}")
        sample_keys = list(stream_templates.keys())[:3]
        for key in sample_keys:
            print(f"  - {key}: {len(stream_templates[key])} students")

        # Test combined template
        all_students = ss.get_all_students()
        combined_template = {"All_Classes_Combined": all_students}
        print(f"✓ Combined template created: {len(combined_template)} template, {len(all_students)} students")

        print("✅ Template data preparation test PASSED")
        return True

    except Exception as e:
        print(f"❌ Template data preparation failed: {e}")
        return False


def main():
    """Run all template generation tests."""
    print("🚀 Template Generation System - Test Suite")
    print("=" * 55)

    tests = [
        ("Excel Template Generation", test_excel_template_generation),
        ("PDF Template Generation", test_pdf_template_generation),
        ("Template Data Preparation", test_template_data_preparation),
    ]

    passed = 0
    total = len(tests)

    for test_name, test_func in tests:
        try:
            if test_func():
                passed += 1
                print(f"✅ {test_name}: PASSED")
            else:
                print(f"❌ {test_name}: FAILED")
        except Exception as e:
            print(f"❌ {test_name}: ERROR - {e}")

    print("\n" + "=" * 55)
    print(f"📊 Test Results: {passed}/{total} tests passed")

    if passed == total:
        print("🎉 All template generation tests passed!")
        print("\n📋 Next steps:")
        print("1. Run migrations: python -m school_system.database.migrations.run_all_migrations")
        print("2. Test the Distribution window in the application")
        print("3. Generate templates and verify they open correctly")
        return 0
    else:
        print("⚠️  Some tests failed. Please check the implementation.")
        print("\n🔧 Troubleshooting:")
        print("- Install required packages: pip install pandas openpyxl fpdf")
        print("- Check file permissions for temporary file creation")
        return 1


if __name__ == "__main__":
    sys.exit(main())